# ----------------------------------------------------------------------------
# Title      : Rogue Base Docker GitHub Actions CD Script
# ----------------------------------------------------------------------------
# This file is part of the rogue software package. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the rogue software package, including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------
# The following environment variables are required for this process:
# secrets.DOCKERHUB_TOKEN

name: Rogue Base Docker Deployment
on: push
  # push:
  #   tags:
  #     - '*'

jobs:
  deploy_docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the git tag from the environmental variables
      # It will used to tag the docker image
      - name: Get release tag
        id: get_tag
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/tags/}"

      # Setup docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Dockerhub
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: tidair
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the docker image
      # - name: Build and push image to Dockerhub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: tidair/rogue-base:${{ steps.get_tag.outputs.tag }}
      #     build-args: branch=${{ steps.get_tag.outputs.tag }}